### ISSUE TITLE
bug: 不支持map的key中带.字符

### ISSUE THREAD

**Issue by CC11001100** [songzhibin97/go-ognl#8]
如下代码，返回了错误的结果： 
```go
package main

import (
	"fmt"
	"github.com/songzhibin97/go-ognl"
)

type Foo struct {
	Bar *Bar
}

type Bar struct {
	Name string
}

func main() {

	m := make(map[string]*Foo)
	m["a.b.c"] = &Foo{Bar: &Bar{Name: "bar name"}}

	get := ognl.Get(m, "a.b.c")
	fmt.Println(get.Value()) // Output: <nil>

}
```

期望：  能够正确返回Foo类型

**Comment by CC11001100** [comment]
参考实现：
[https://github.com/spf13/viper#unmarshaling](https://github.com/spf13/viper#unmarshaling)
![image](https://github.com/songzhibin97/go-ognl/assets/12819457/ff6dc6d2-4c93-4801-9d20-105beee26417)

**Comment by songzhibin97** [comment]
你可以尝试解决并提交pr吗, thx,如果可以我将分配给你 @CC11001100

**Comment by CC11001100** [comment]
我谢谢您

**Comment by CC11001100** [comment]
让我看一眼代码先

**Comment by CC11001100** [comment]
想到了一种情况，如果要支持map中的key含有.的话，则问题又来了，那下面的代码应该选中什么呢。。。
```go
package main

import (
	"fmt"
	"github.com/songzhibin97/go-ognl"
)

type Foo struct {
	Bar *Bar
}

type Bar struct {
	Name string
}

func main() {

	m := make(map[string]*Foo)
	m["Foo.Bar.Name"] = &Foo{Bar: &Bar{Name: "bar name 001"}}
	m["Foo"] = &Foo{Bar: &Bar{Name: "bar name 002"}}

	get := ognl.Get(m, "Foo.Bar.Name")
	fmt.Println(get.Value()) // Output: bar name 002

}
```

**Comment by songzhibin97** [comment]
> 想到了一种情况，如果要支持map中的key含有.的话，则问题又来了，那下面的代码应该选中什么呢。。。
> 
> ```go
> package main
> 
> import (
> 	"fmt"
> 	"github.com/songzhibin97/go-ognl"
> )
> 
> type Foo struct {
> 	Bar *Bar
> }
> 
> type Bar struct {
> 	Name string
> }
> 
> func main() {
> 
> 	m := make(map[string]*Foo)
> 	m["Foo.Bar.Name"] = &Foo{Bar: &Bar{Name: "bar name 001"}}
> 	m["Foo"] = &Foo{Bar: &Bar{Name: "bar name 002"}}
> 
> 	get := ognl.Get(m, "Foo.Bar.Name")
> 	fmt.Println(get.Value()) // Output: bar name 002
> 
> }
> ```

是否可以在`.`、`#` 增加转义符来达到预期的效果呢

**Comment by CC11001100** [comment]
> > 想到了一种情况，如果要支持map中的key含有.的话，则问题又来了，那下面的代码应该选中什么呢。。。
> > ```go
> > package main
> > 
> > import (
> > 	"fmt"
> > 	"github.com/songzhibin97/go-ognl"
> > )
> > 
> > type Foo struct {
> > 	Bar *Bar
> > }
> > 
> > type Bar struct {
> > 	Name string
> > }
> > 
> > func main() {
> > 
> > 	m := make(map[string]*Foo)
> > 	m["Foo.Bar.Name"] = &Foo{Bar: &Bar{Name: "bar name 001"}}
> > 	m["Foo"] = &Foo{Bar: &Bar{Name: "bar name 002"}}
> > 
> > 	get := ognl.Get(m, "Foo.Bar.Name")
> > 	fmt.Println(get.Value()) // Output: bar name 002
> > 
> > }
> > ```
> 
> 是否可以在`.`、`#` 增加转义符来达到预期的效果呢

cool
